name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build static site
      run: |
        mkdir -p public
        echo "<html><body><h1>Bad Practices Deployed!</h1></body></html>" > public/index.html

    - name: Deploy using git
      run: |
        git config user.name "bot"
        git config user.email "bot@example.com"
        git add public
        git commit -m "Deploy Bad Practices" || echo "Nothing to commit"
        git push origin main