name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y wget

    - name: Prepare public folder
      run: |
        mkdir public
        echo "<html><body><h1>My Page</h1></body></html>" > public/index.html

    - name: Deploy
      run: |
        git config user.name "bot"
        git config user.email "bot@example.com"
        git add .
        git commit -m "Deploy"
        git push
